### ISSUE TITLE
Proposal: provide a default test-suite

### ISSUE THREAD

**Issue by markpdeeson** [teamdeeson/d8-quickstart#2]
## Description
This is a proposal to provide a test-suite with the quickstart project which validates the expected functionality provided by this project.

**Comment by johnennewdeeson** [comment]
I had a go at writing a unit test over the weekend. Looking at the root phpunit.xml file it looks like the process should be that we just execute the following in the project root to run all custom module phpunit tests:

`./vendor/bin/phpunit`

However this is currently failing due to Drupal Tests bootstrap not being included.
